version: 2.1

orbs:
  node: circleci/node@4.9.0

jobs:
  test-and-build:
    docker:
      - image: cimg/node:16.4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests and build
          command: npm test && npm run build

workflows:
  test-and-build:
    jobs:
      - test-and-build
